version: 2

project_name: samcro1967/glance

release:
  prerelease: false

checksum:
  disable: true

builds:
  - binary: glance
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w -X github.com/samcro1967/glance/internal/glance.buildVersion={{ .Tag }} -X github.com/samcro1967/glance/internal/glance.buildRevision={{ .FullCommit }}

dockers_v2:
  - images:
      - "ghcr.io/{{ .ProjectName }}"
    tags:
      - "{{ .Tag }}"
      - "latest"
    dockerfile: Dockerfile.goreleaser
    platforms:
      - linux/amd64
      - linux/arm64
